# Custom Appveyor settings

image: Visual Studio 2017

matrix:
  # immediately finish build on failure
  fast_finish: true

# Scripts that run after cloning
install:
  - ps: Install-Module -Name InvokeBuild, PowerShellGet, Pester, ModuleBuilder -SkipPublisherCheck -Force
build_script:
  - ps: |
      $ErrorActionPreference = 'Stop'
      if ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
        Invoke-Build -Configuration 'Release'
      } else {
        Invoke-Build -Configuration 'Development'
      }
      Compress-Archive -Path ".\bin\$Env:APPVEYOR_PROJECT_NAME" -DestinationPath ".\$Env:APPVEYOR_PROJECT_NAME.zip"
      Push-AppveyorArtifact ".\$Env:APPVEYOR_PROJECT_NAME.zip"

environment:
  NugetApiKey:
    secure: SYfPel8xbp/wq5ZKzXcvSe8FjsFSwkqOwUP4sykB/FZYSgUyoeLFmcD0ngR+6DkG
